---
- name: Add aliases into .bashrc
  ansible.builtin.blockinfile:
    path: "{{ '/root' if item == 'root' else '/home/' + item }}/.bashrc"
    block: |
      {% if item != 'root' %}
      alias sudo='sudo '
      {% endif %}

      {% for alias_name, alias_command in bash_aliases_list.items() %}
      alias {{ alias_name }}='{{ alias_command }}'
      {% endfor %}
  loop: "{{ bash_aliases_users }}"
