---
- name: Remove default users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ __accounts_users_to_remove }}"
  when: accounts_clean_default_users | bool

- name: Update root password
  no_log: true
  ansible.builtin.user:
    name: root
    password: "{{ accounts_root_pass }}"
  when: accounts_root_pass | length > 0

- name: Configure root SSH key
  no_log: true
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ accounts_root_ssh_pub_key }}"
    exclusive: true
  when: accounts_list_sudo_users | length == 0

- name: Import sudo_users.yaml
  ansible.builtin.import_tasks: sudo_users.yaml
  when: accounts_list_sudo_users | length > 0

- name: Apply .bashrc from template for all users
  ansible.builtin.template:
    src: bashrc.j2
    dest: "{{ (item.login == 'root') | ternary('/root', '/home/' ~ item.login) }}/.bashrc"
    owner: "{{ item.login }}"
    group: "{{ item.login }}"
    mode: '0644'
  loop: "{{ [{'login': 'root'}] + accounts_list_sudo_users }}"
