---
- name: Set hostname
  no_log: true
  ansible.builtin.hostname:
    name: "{{ hostname_value }}"

- name: Update /etc/hosts from template
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '644'
