---
- name: Apt update and upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"

- name: Install packages
  loop: "{{ base_pkgs + extra_pkgs }}"
  ansible.builtin.apt:
    name: "{{ item }}"
