---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    update_cache: true
    state: present

- name: Creating a config for sshd
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban service