---
- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow loopback traffic
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Configure firewall rules for trusted IPs
  when: iptables_allowed_ips | length > 0
  block:
    - name: Allow new connections via SSH
      loop: "{{ iptables_allowed_ips }}"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ iptables_ssh_port }}"
        ctstate: NEW
        jump: ACCEPT
        source: "{{ item }}"

    - name: Allow ICMP echo requests
      loop: "{{ iptables_allowed_ips }}"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: icmp
        jump: ACCEPT
        source: "{{ item }}"
        icmp_type: 8

- name: Add firewall rules to LOGGING chain
  tags: skip-iptables-log
  block:
    - name: Create the user-defined chain LOGGING
      ansible.builtin.iptables:
        chain: "{{ iptables_name_logging_chain }}"
        chain_management: true

    - name: Add a redirection rule to LOGGING
      ansible.builtin.iptables:
        chain: INPUT
        jump: "{{ iptables_name_logging_chain }}"

    - name: Log invalid packets
      ansible.builtin.iptables:
        chain: "{{ iptables_name_logging_chain }}"
        action: append
        limit: "{{ iptables_logging_limit }}"
        limit_burst: "{{ iptables_logging_limit_burst }}"
        log_prefix: "IPTABLES INVALID:  "
        ctstate: INVALID

    - name: Log dropped packets
      ansible.builtin.iptables:
        chain: "{{ iptables_name_logging_chain }}"
        action: append
        limit: "{{ iptables_logging_limit }}"
        limit_burst: "{{ iptables_logging_limit_burst }}"
        log_prefix: "IPTABLES DROP:  "

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Set the policy for the FORWARD chain to DROP
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    update_cache: true
    state: present
