---
- name: Remove disclaimer
  ansible.builtin.file:
    path: /etc/motd
    state: absent

- name: Copy sysinfo
  ansible.builtin.copy:
    src: sysinfo
    dest: /etc/update-motd.d/sysinfo
    owner: root
    group: root
    mode: '744'
