---
- name: Delete custom Cloudinit config
  ansible.builtin.file:
    path: "{{ __ssh_config_path }}/60-cloudimg-settings.conf"
    state: absent

- name: Create ssh group
  ansible.builtin.group:
    name: "{{ ssh_group }}"
    state: present
    system: true
  when: not ssh_is_root_allowed | bool

- name: Apply sshd.conf from template
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: "{{ __ssh_config_path }}/{{ __ssh_config_name }}"
    owner: root
    group: root
    mode: '600'
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Restart ssh service
    - Restart ssh.socket
