---
- name: Find files in sshd_config.d
  ansible.builtin.find:
    paths: "{{ __ssh_config_path }}"
    file_type: file
  register: __ssh_list_files

- name: Delete the contents of sshd_config.d
  when: __ssh_list_files.matched > 0
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ __ssh_list_files.files }}"

- name: Create ssh group
  ansible.builtin.group:
    name: "{{ ssh_group }}"
    state: present
    system: true
  when: not ssh_is_root_allowed | bool

- name: Apply sshd.conf from template
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: "{{ __ssh_config_path }}/{{ __ssh_config_name }}"
    owner: root
    group: root
    mode: '600'
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Restart ssh service
    - Restart ssh.socket
