---
- name: Find files in sshd_config.d
  ansible.builtin.find:
    paths: "{{ __ssh_config_path }}"
    file_type: file
  register: list_files

- name: Delete the contents of sshd_config.d
  when: list_files.matched > 0
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ list_files.files }}"

- name: Create ssh group
  ansible.builtin.group:
    name: "{{ ssh_group }}"
    state: present
    system: true

- name: Apply sshd.conf from template
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: "{{ __ssh_config_path }}/{{ __ssh_config_name }}"
    owner: root
    group: root
    mode: '644'
  notify: Restart ssh service
