---
driver:
  name: molecule-proxmox
  options:
    proxmox_secrets: $HOME/.molecule/proxmox-secrets.yml
    full: true

platforms:
  - name: "molecule-${os}"
    template_name: ${os}-tmp
    ipconfig:
      ipconfig0: 'ip=dhcp'

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 2
    ANSIBLE_ROLES_PATH: "../../roles"
