---
- name: Set timezone
  community.general.timezone:
    name: Europe/Kyiv

- name: Configure system hostname
  block:
  - name: Set hostname
    no_log: true
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: Update /etc/hosts from template
    ansible.builtin.template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644

- name: Copy zero_space scripts for VirtualBox VMs
  ansible.builtin.copy:
    src: zero_space
    dest: /usr/local/bin/zero_space
    owner: root
    group: root
    mode: 0755
  when: ansible_virtualization_type == 'virtualbox'

- name: Copy 00-common-aliases.sh
  ansible.builtin.copy:
    src: 00-common-aliases.sh
    dest: /etc/profile.d/00-common-aliases.sh
    owner: root
    group: root
    mode: 0755