---
- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Copy zero_space script for VirtualBox and VMware VMs
  ansible.builtin.copy:
    src: zero_space
    dest: /usr/local/bin/zero_space
    owner: root
    group: root
    mode: '755'
  when: |
    ansible_virtualization_type == 'virtualbox' or
    ansible_virtualization_type == 'VMware'
