---
- name: Set timezone
  community.general.timezone:
    name: Europe/Kyiv

- name: Copy zero_space scripts for VirtualBox VMs
  ansible.builtin.copy:
    src: zero_space
    dest: /usr/local/bin/zero_space
    owner: root
    group: root
    mode: '755'
  when: ansible_virtualization_type == 'virtualbox'

- name: Copy alias scripts
  loop: "{{ script_aliases }}"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    owner: root
    group: root
    mode: '755'
