---
- name: Apt update and upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ __utilities_core + utilities_extra }}"
